services:
  db:
    image: postgres:16-alpine
    container_name: bibliotheque-db
    environment:
      POSTGRES_USER: dit
      POSTGRES_PASSWORD: dit_password
      POSTGRES_DB: bibliotheque
    ports:
      - "5432:5432"
    volumes:
      - bibliotheque_data:/var/lib/postgresql/data

volumes:
  bibliotheque_data:
  