services:
  db:
    image: postgres:16-alpine
    container_name: bibliotheque-db
    environment:
      POSTGRES_USER: dit
      POSTGRES_PASSWORD: dit_password
      POSTGRES_DB: bibliotheque
    ports:
      - "5432:5432"
    volumes:
      - bibliotheque_data:/var/lib/postgresql/data

  livres:
    build: ./services/livres
    container_name: service-livres
    environment:
      DATABASE_URL: postgresql://dit:dit_password@db:5432/bibliotheque
    ports:
      - "8001:8001"
    depends_on:
      - db

  utilisateurs:
    build: ./services/utilisateurs
    container_name: service-utilisateurs
    environment:
      DATABASE_URL: postgresql://dit:dit_password@db:5432/bibliotheque
    ports:
      - "8002:8002"
    depends_on:
      - db

  emprunts:
    build: ./services/emprunts
    container_name: service-emprunts
    environment:
      DATABASE_URL: postgresql://dit:dit_password@db:5432/bibliotheque
      URL_SERVICE_LIVRES: http://livres:8001
      URL_SERVICE_UTILISATEURS: http://utilisateurs:8002
    ports:
      - "8003:8003"
    depends_on:
      - db
      - livres
      - utilisateurs

volumes:
  bibliotheque_data:
